version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - react-node-network
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - react-node-network

networks:
  react-node-network: